import Providers from "@/components/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import ConfigureLayout from "@/components/ConfigureLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MongoDB Login Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ConfigureLayout>
            <div className="bg-zinc-950 text-gray-300">{children}</div>
          </ConfigureLayout>
        </Providers>
      </body>
    </html>
  );
}